Traceback (most recent call last):
  File "/users/stud09/martinsd/proj/sar2watermask/modules/getRecentScenes.py", line 22, in <module>
    platformname='Sentinel-1')
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 135, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 249, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 278, in _load_subquery
    response = self.session.post(url, {'q': query}, auth=self.session.auth)
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/users/stud09/martinsd/local/miniconda2/envs/snappy/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='scihub.copernicus.eu', port=443): Max retries exceeded with url: /dhus/search?format=json&rows=100&start=0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fde9e59f950>: Failed to establish a new connection: [Errno 110] Connection timed out',))
